# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.8885, 0.0020, 0.5024, 0.1725, 0.3025, 0.2762, 0.0172],
        [0.1262, 0.9722, 0.6127, 0.0154, 0.6964, 0.6053, 0.1322],
        [0.2098, 0.6509, 0.2416, 0.9946, 0.3072, 0.5248, 0.6551],
        [0.4843, 0.4796, 0.9792, 0.5696, 0.6585, 0.9133, 0.4271],
        [0.7709, 0.5117, 0.6696, 0.9474, 0.9270, 0.6641, 0.1708],
        [0.7440, 0.9807, 0.3946, 0.8556, 0.1303, 0.3240, 0.6714],
        [0.2860, 0.1534, 0.3971, 0.2833, 0.1014, 0.5753, 0.0664]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
random_tensor2 = torch.rand(1,7)
# Perform matrix multiplication
res = torch.matmul(random_tensor, random_tensor2.T)
res

tensor([[0.6170],
        [0.9580],
        [1.3381],
        [1.6383],
        [1.5986],
        [1.2660],
        [0.6414]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
random_seed=0
torch.manual_seed(0)

# Create two random tensors
random_tensor= torch.rand(7,7)

random_tensor2= torch.rand(1,7)

# Matrix multiply tensors
res = torch.matmul(random_tensor, random_tensor2.T)
res


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
random_seed =1234
device ="cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
# Set random seed
random_seed=1234
torch.manual_seed(random_seed)

# Check for access to GPU
device ="cuda" if torch.cuda.is_available() else "cpu"
device
# Create two random tensors on GPU
random_tensor= torch.rand(2,3).to(device)
random_tensor2= torch.rand(2,3).to(device)
random_tensor, random_tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
res = torch.matmul(random_tensor, random_tensor2.T)
res, res.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
res.max()
# Find min
res.min()

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
maxI=res.argmax()

# Find arg min
minI=res.argmin()
maxI, minI

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1,1,1,10)

# Remove single dimensions
random_tensorN = random_tensor.squeeze();

# Print out tensors and their shapes
random_tensor , random_tensor.shape, random_tensorN, random_tensorN.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))